version: "2"
services:
  web-service:
    build:
      context: .
      dockerfile: springboot.dockerfile
    container_name: smweb-container
    ports:
      - "8088:8888"
    networks:
      - net-spring-db
    depends_on:
      - db-service
    links:
      - db-service
  db-service:
    build:
      context: . # dockerfile文件的目录
      dockerfile: springboot.dockerfile # 重命名dockerfile的文件名
    container_name: mysql-container
    restart: always
    ports:
      - "3306:3306"
    networks:
      - net-spring-db
    environment:
          MYSQL_DATABASE: rbac
          MYSQL_USER: h2t
          MYSQL_PASSWORD: 123456
networks:
  net-spring-db:
    driver: bridge