##¶Ë¿ÚºÅ
server:
    port: 8888

##Êý¾Ý¿âurl
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
    mapper-locations: classpath*:/mapper/*.xml
    type-aliases-package: com.example.springbootdemo.entity
    type-aliases-super-type: java.lang.Object
    type-handlers-package: com.example.springbootdemo.typeHandler
    type-enums-package: com.example.springbootdemo.enums

